#Version 1.1
#Copyright © 2023 by Shad0wsense. All rights reserved. This material may not be published, broadcast, rewritten or redistributed without permission.

startScrambleEvent:
  - "&8&l[ &a&lSCRAMBLEEVENT &8&l] ➥"
  - "&fI skal skrive &b%word%"


vandtScrambleEvent:
  - "&8&l[ &a&lSCRAMBLEEVENT &8&l] &c%player% &fvandt ScrambleEventet og modtog &a%penge%"


permissionDenied: "&8&l[ &a&lSCRAMBLEEVENT &8&l] &cDu har ikke adgang."

beløning:
  random:
    boolean: true
    penge:
      min: 0
      max: 30000
      default: 300

autoscramblestart:
  #100 = 5 sekunder
  delay: 3000
  enabled: false

words:
  - iskoldcool
  - Shad0wsense
  - Nydt
  - LildaddyD
